# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'risk_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 450)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.logo = QtGui.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(0, 0, 371, 211))
        self.logo.setText(_fromUtf8(""))
        self.logo.setPixmap(QtGui.QPixmap(_fromUtf8("risk.jpg")))
        self.logo.setScaledContents(True)
        self.logo.setObjectName(_fromUtf8("logo"))
        self.console_window = QtGui.QTextEdit(self.centralwidget)
        self.console_window.setGeometry(QtCore.QRect(380, 10, 401, 411))
        self.console_window.setReadOnly(True)
        self.console_window.setObjectName(_fromUtf8("console_window"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 220, 372, 198))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.main = QtGui.QVBoxLayout(self.layoutWidget)
        self.main.setObjectName(_fromUtf8("main"))
        self.options = QtGui.QVBoxLayout()
        self.options.setObjectName(_fromUtf8("options"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.single_radio = QtGui.QRadioButton(self.layoutWidget)
        self.single_radio.setObjectName(_fromUtf8("single_radio"))
        self.verticalLayout_2.addWidget(self.single_radio)
        self.auto_radio = QtGui.QRadioButton(self.layoutWidget)
        self.auto_radio.setObjectName(_fromUtf8("auto_radio"))
        self.verticalLayout_2.addWidget(self.auto_radio)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.acount_spinbox = QtGui.QSpinBox(self.layoutWidget)
        self.acount_spinbox.setMinimum(1)
        self.acount_spinbox.setObjectName(_fromUtf8("acount_spinbox"))
        self.horizontalLayout.addWidget(self.acount_spinbox)
        self.dcount_spinbox = QtGui.QSpinBox(self.layoutWidget)
        self.dcount_spinbox.setMinimum(1)
        self.dcount_spinbox.setObjectName(_fromUtf8("dcount_spinbox"))
        self.horizontalLayout.addWidget(self.dcount_spinbox)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.roll_button = QtGui.QPushButton(self.layoutWidget)
        self.roll_button.setObjectName(_fromUtf8("roll_button"))
        self.verticalLayout.addWidget(self.roll_button)
        self.exit_button = QtGui.QPushButton(self.layoutWidget)
        self.exit_button.setObjectName(_fromUtf8("exit_button"))
        self.verticalLayout.addWidget(self.exit_button)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.options.addLayout(self.horizontalLayout_2)
        self.main.addLayout(self.options)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.fouroneseven = QtGui.QVBoxLayout()
        self.fouroneseven.setObjectName(_fromUtf8("fouroneseven"))
        self.one_button = QtGui.QPushButton(self.layoutWidget)
        self.one_button.setObjectName(_fromUtf8("one_button"))
        self.fouroneseven.addWidget(self.one_button)
        self.four_button = QtGui.QPushButton(self.layoutWidget)
        self.four_button.setObjectName(_fromUtf8("four_button"))
        self.fouroneseven.addWidget(self.four_button)
        self.seven_button = QtGui.QPushButton(self.layoutWidget)
        self.seven_button.setObjectName(_fromUtf8("seven_button"))
        self.fouroneseven.addWidget(self.seven_button)
        self.horizontalLayout_3.addLayout(self.fouroneseven)
        self.eightfivetwo = QtGui.QVBoxLayout()
        self.eightfivetwo.setObjectName(_fromUtf8("eightfivetwo"))
        self.two_button = QtGui.QPushButton(self.layoutWidget)
        self.two_button.setObjectName(_fromUtf8("two_button"))
        self.eightfivetwo.addWidget(self.two_button)
        self.five_button = QtGui.QPushButton(self.layoutWidget)
        self.five_button.setObjectName(_fromUtf8("five_button"))
        self.eightfivetwo.addWidget(self.five_button)
        self.eight_button = QtGui.QPushButton(self.layoutWidget)
        self.eight_button.setObjectName(_fromUtf8("eight_button"))
        self.eightfivetwo.addWidget(self.eight_button)
        self.horizontalLayout_3.addLayout(self.eightfivetwo)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.ninesixthree = QtGui.QVBoxLayout()
        self.ninesixthree.setObjectName(_fromUtf8("ninesixthree"))
        self.three_button = QtGui.QPushButton(self.layoutWidget)
        self.three_button.setObjectName(_fromUtf8("three_button"))
        self.ninesixthree.addWidget(self.three_button)
        self.six_button = QtGui.QPushButton(self.layoutWidget)
        self.six_button.setObjectName(_fromUtf8("six_button"))
        self.ninesixthree.addWidget(self.six_button)
        self.nine_button = QtGui.QPushButton(self.layoutWidget)
        self.nine_button.setObjectName(_fromUtf8("nine_button"))
        self.ninesixthree.addWidget(self.nine_button)
        self.horizontalLayout_4.addLayout(self.ninesixthree)
        self.zeroclear = QtGui.QVBoxLayout()
        self.zeroclear.setObjectName(_fromUtf8("zeroclear"))
        self.clear_button = QtGui.QPushButton(self.layoutWidget)
        self.clear_button.setObjectName(_fromUtf8("clear_button"))
        self.zeroclear.addWidget(self.clear_button)
        self.zero = QtGui.QPushButton(self.layoutWidget)
        self.zero.setObjectName(_fromUtf8("zero"))
        self.zeroclear.addWidget(self.zero)
        self.horizontalLayout_4.addLayout(self.zeroclear)
        self.main.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.single_radio.setText(_translate("MainWindow", "Single Attack", None))
        self.auto_radio.setText(_translate("MainWindow", "Auto Attack", None))
        self.roll_button.setText(_translate("MainWindow", "Roll", None))
        self.exit_button.setText(_translate("MainWindow", "Exit", None))
        self.one_button.setText(_translate("MainWindow", "1", None))
        self.four_button.setText(_translate("MainWindow", "4", None))
        self.seven_button.setText(_translate("MainWindow", "7", None))
        self.two_button.setText(_translate("MainWindow", "2", None))
        self.five_button.setText(_translate("MainWindow", "5", None))
        self.eight_button.setText(_translate("MainWindow", "8", None))
        self.three_button.setText(_translate("MainWindow", "3", None))
        self.six_button.setText(_translate("MainWindow", "6", None))
        self.nine_button.setText(_translate("MainWindow", "9", None))
        self.clear_button.setText(_translate("MainWindow", "Clear", None))
        self.zero.setText(_translate("MainWindow", "0", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

